baseURL = "https://mx.shoogle.net/mexico/"
languageCode = "es"
title = "México"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "mexico"

[taxonomies]
  shop = "shops"

